// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'bootstrap.min'], function($) {
    $(function() {
      $('.carousel').carousel();
      $("a[rel=popover]").popover();
    });
  });

}).call(this);
