// Generated by CoffeeScript 1.3.3
(function() {

  define(["jquery", "jquery.fancybox.pack", "jquery.fancybox-buttons", "jquery.fancybox-media", "jquery.fancybox-thumbs"], function($) {
    $(function() {
      $('.fancybox').fancybox({
        autoSize: false,
        height: '90%',
        width: 640,
        afterShow: function() {
          this.resize();
        }
      });
    });
  });

}).call(this);
