// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery'], function($) {
    $(function() {
      $.ajax({
        url: '/tweets/',
        type: 'GET',
        success: function(data, textStatus, xhr) {
          $('.tweets div').html(data);
        }
      });
    });
  });

}).call(this);
